name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  dewo_dd_synthetic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Datadog Synthetic Tests
        uses: DataDog/synthetics-ci-github-action@v2.0.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          datadog_site: "us5.datadoghq.com"
          public_ids: |
            hui-6q5-cmq
